"""create query attempts table

Revision ID: 025bf20ce7b2
Revises: c4f4b1d7a9d2
Create Date: 2026-09-03 11:49:05.214849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '025bf20ce7b2'
down_revision: Union[str, Sequence[str], None] = 'c4f4b1d7a9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_record_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('sql_query', sa.Text(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('failure_category', sa.String(length=64), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['query_record_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_attempts_id'), 'query_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_query_attempts_query_record_id'), 'query_attempts', ['query_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_attempts_query_record_id'), table_name='query_attempts')
    op.drop_index(op.f('ix_query_attempts_id'), table_name='query_attempts')
    op.drop_table('query_attempts')
    # ### end Alembic commands ###
