"""change workspace key to string

Revision ID: 0db33ef1b040
Revises: 9854c49ed87d
Create Date: 2026-07-19 21:04:13.427629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db33ef1b040'
down_revision: Union[str, Sequence[str], None] = '9854c49ed87d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'workspace_key',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False,
               postgresql_using="workspace_key::text",
               )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'workspace_key',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
