"""workspace relationship added to session

Revision ID: d014821337b9
Revises: 5ff6123ebc21
Create Date: 2026-07-20 21:28:57.633182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd014821337b9'
down_revision: Union[str, Sequence[str], None] = '5ff6123ebc21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_sessions_workspace_id'), 'sessions', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'sessions', 'workspaces', ['workspace_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_index(op.f('ix_sessions_workspace_id'), table_name='sessions')
    op.drop_column('sessions', 'workspace_id')
    # ### end Alembic commands ###
